export const CHUNK_SIZE = 16;
export const CHUNK_HEIGHT = 256;
export const RENDER_DISTANCE = 8; // chunks
export const SEA_LEVEL = 64;
export const GRAVITY = -28;
export const JUMP_FORCE = 9;
export const PLAYER_SPEED = 5;
export const SPRINT_MULTIPLIER = 1.6;
export const PLAYER_HEIGHT = 1.8;
export const PLAYER_WIDTH = 0.6;
export const DAY_LENGTH = 20 * 60; // 20 minutes in seconds
export const MAX_HEALTH = 20;
export const MAX_HUNGER = 20;
export const HOTBAR_SIZE = 9;
export const INVENTORY_ROWS = 4;
export const INVENTORY_COLS = 9;
export const TICK_RATE = 20; // ticks per second
export const REACH_DISTANCE = 5;
export const FOV = 75;
export const NEAR_PLANE = 0.05;
export const FAR_PLANE = 1000;
